name: Deploy to Cloudflare Pages

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Call deploy hook
        env:
          CF_DEPLOY_HOOK: ${{ secrets.CF_DEPLOY_HOOK }}
        run: |
          curl -X POST "$CF_DEPLOY_HOOK"
